# `dependabot.yml` file with updates

version: 2
updates:
  # GitHub actions themselves
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
